#ifndef FLUX_PWR_MANAGER_CONSTANTS_H
#define FLUX_PWR_MANAGER_CONSTANTS_H
// Power Monitor
#define INTERVAL_SEC 0           // Seconds part of the interval
#define INTERVAL_NSEC 250000000L // Nanoseconds part of the interval (500 ms)
#define MAX_FILENAME_SIZE 256

// FFT
#define SAMPLING_RATE 4 // SAMPLING RATE IN A SECOND
#define THIRTY_SECONDS (30 * SAMPLING_RATE)
#define FOURTY_SECONDS (40 * SAMPLING_RATE)
#define SIXTY_SECONDS (60 * SAMPLING_RATE)
#define ONE_TWNETY_SECONDS (120 * SAMPLING_RATE)
#define NINTY_SECONDS (90 * SAMPLING_RATE)
#define THREE_MINUTES (180 * SAMPLING_RATE)
#define SIX_MINUTES (180 * 2 * SAMPLING_RATE)
#define THIRTY_MINUTES (180 * 10 * SAMPLING_RATE)
#define FFT_BUFFER_SIZE SIX_MINUTES
#define FFT_SAMPLING_PERIOD THIRTY_SECONDS
// NODE Power INFO
#define MAX_NODE_POWER 600
#define MIN_NODE_POWER 500

#endif
