#ifndef FLUX_PWR_MGR_SYSTEM_CONFIG_H
#define FLUX_PWR_MGR_SYSTEM_CONFIG_H
#define NUM_OF_GPUS 4 
#define NUM_OF_MEMS 2
#define NUM_OF_CPUS 2
#define MAX_GPU_POWER 300
#define MIN_GPU_POWER 300
#endif

